2023-07-02 10:32:19,977        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 10:32:19,978        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-02 10:32:19,979        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 10:32:19,980        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 10:32:20,017        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:02:48,312        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:02:48,313        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-02 20:02:48,314        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:02:48,315        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:02:48,417        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:03:37,179        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:03:37,180        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:03:37,180        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:03:37,181        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:03:37,285        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:09:34,831        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:09:34,832        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:09:34,832        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:09:34,833        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:09:34,860        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:11:30,606        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:11:30,607        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:11:30,608        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:11:30,608        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:11:30,635        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:18:15,641        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:18:15,642        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:18:15,642        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:18:15,643        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:18:15,707        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:24:01,614        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:24:01,614        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:24:01,615        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:24:01,616        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:24:01,692        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:29:54,090        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:29:54,091        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:29:54,092        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:29:54,093        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:29:54,120        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:34:43,301        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:34:43,301        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:34:43,302        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:34:43,303        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:34:43,331        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:43:10,279        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:43:10,280        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:43:10,280        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:43:10,281        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:43:10,307        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:44:11,947        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:44:11,948        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-02 20:44:11,949        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:44:11,950        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:44:12,052        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 20:44:36,065        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 54384)
2023-07-02 20:44:36,068        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 54385)
2023-07-02 20:44:36,797        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 54384)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-02 20:46:07,112        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:46:07,113        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 20:46:07,114        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 20:46:07,114        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 20:46:07,191        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 21:58:54,345        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 21:58:54,346        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 21:58:54,346        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 21:58:54,347        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 21:58:54,392        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:03:34,546        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:03:34,546        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 22:03:34,547        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:03:34,548        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:03:34,576        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:04:34,135        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:04:34,136        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 22:04:34,136        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:04:34,137        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:04:34,165        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:06:19,136        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:06:19,136        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 22:06:19,137        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:06:19,138        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:06:19,166        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:07:33,667        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:07:33,668        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 22:07:33,668        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:07:33,669        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:07:33,696        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:15:50,346        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции port).Вызов из функции main
2023-07-02 22:15:50,346        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 22:15:50,346        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:15:50,362        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции port).Вызов из функции main
2023-07-02 22:15:50,377        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:32:54,322        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции port).Вызов из функции main
2023-07-02 22:32:54,322        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 22:32:54,322        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:32:54,338        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции port).Вызов из функции main
2023-07-02 22:32:54,354        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:47:51,136        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции port).Вызов из функции main
2023-07-02 22:47:51,136        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['D:\\projects\\pythonProject\\server\\server.py']
2023-07-02 22:47:51,136        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:47:51,136        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции port).Вызов из функции main
2023-07-02 22:47:51,183        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:49:24,158        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:49:24,158        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-02 22:49:24,160        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 22:49:24,160        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 22:49:24,263        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 22:49:43,318        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56229)
2023-07-02 22:49:43,335        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56230)
2023-07-02 22:49:43,337        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 56229)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-02 23:22:42,429        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 23:22:42,429        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-02 23:22:42,430        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 23:22:42,431        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 23:22:42,455        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 23:22:57,108        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56730)
2023-07-02 23:22:57,213        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56731)
2023-07-02 23:22:57,215        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1100, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 56730)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-02 23:38:54,051        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 23:38:54,052        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-02 23:38:54,053        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 23:38:54,054        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 23:38:54,077        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 23:39:10,002        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56977)
2023-07-02 23:39:10,015        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56978)
2023-07-02 23:39:10,017        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 56977)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-02 23:40:27,777        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 23:40:27,777        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-02 23:40:27,777        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-02 23:40:27,777        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-02 23:40:27,809        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-02 23:40:42,942        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56997)
2023-07-02 23:40:42,957        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 56998)
2023-07-02 23:40:43,468        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1172, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 56997)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 00:05:26,958        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 00:05:26,958        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 00:05:26,973        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 00:05:26,973        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 00:05:27,005        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 00:05:41,690        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 57216)
2023-07-03 00:05:41,690        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 57217)
2023-07-03 00:05:42,206        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1296, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 57216)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 21:44:42,165        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 21:44:42,171        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 21:44:42,172        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 21:44:42,172        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 21:44:42,231        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 21:44:58,154        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52082)
2023-07-03 21:44:58,155        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52083)
2023-07-03 21:44:58,666        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1320, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52082)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 21:55:22,748        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 21:55:22,749        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 21:55:22,750        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 21:55:22,750        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 21:55:22,778        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 21:55:35,699        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52214)
2023-07-03 21:55:35,706        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52215)
2023-07-03 21:55:36,218        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52214)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 21:55:36,218        INFO         server.py                 Получено сообщение {'action': 'presence', 'time': 1688410535.714187, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:03:05,926        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:03:05,927        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 22:03:05,928        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 22:03:05,928        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:03:06,009        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 22:03:19,326        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52315)
2023-07-03 22:03:19,328        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52316)
2023-07-03 22:03:19,837        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52315)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:03:19,837        INFO         server.py                 Получено сообщение {'action': 'presence', 'time': 1688410999.3365898, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:13:55,783        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:13:55,784        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 22:13:55,784        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 22:13:55,785        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:13:55,813        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 22:14:09,126        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52370)
2023-07-03 22:14:09,126        INFO         server.py                 Сокет клиента [<socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52370)>]
2023-07-03 22:14:09,133        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52371)
2023-07-03 22:14:09,134        INFO         server.py                 Сокет клиента [<socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52370)>, <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52371)>]
2023-07-03 22:14:09,638        INFO         server.py                 Сокет клиента [<socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52370)>, <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52371)>]
2023-07-03 22:14:09,645        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52370)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:14:09,646        INFO         server.py                 Получено сообщение {'action': 'presence', 'time': 1688411649.136316, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:17:33,797        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:17:33,798        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 22:17:33,799        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 22:17:33,800        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:17:33,826        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 22:17:48,784        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52389)
2023-07-03 22:17:48,785        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52390)
2023-07-03 22:17:49,304        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52389)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:17:49,304        INFO         server.py                 response: {'action': 'presence', 'time': 1688411868.7949805, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:17:49,304        INFO         server.py                 client_with_message: <socket.socket fd=1308, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52389)>
2023-07-03 22:23:26,500        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:23:26,501        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 22:23:26,502        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 22:23:26,503        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:23:26,532        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 22:23:36,502        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52422)
2023-07-03 22:23:36,503        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52423)
2023-07-03 22:23:37,015        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52422)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:23:37,016        INFO         server.py                 response: {'action': 'presence', 'time': 1688412216.5125248, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:23:37,017        INFO         server.py                 client_with_message: <socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52422)>
2023-07-03 22:23:37,026        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688412216.5125248, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:23:37,026        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 22:23:37,026        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 22:23:37,035        DEBUG        server.py                 Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-07-03 22:23:37,039        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52422)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:23:37,041        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1300, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52423)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:23:37,041        INFO         server.py                 response: {'action': 'presence', 'time': 1688412216.5125248, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:23:37,042        INFO         server.py                 client_with_message: <socket.socket fd=1300, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52423)>
2023-07-03 22:23:37,042        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688412216.5125248, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:23:37,042        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 22:23:37,042        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 22:23:37,044        DEBUG        server.py                 Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2023-07-03 22:23:37,047        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1300, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52423)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:25:11,463        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52430)
2023-07-03 22:25:11,465        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52431)
2023-07-03 22:25:11,974        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:11,974        INFO         server.py                 response: {'action': 'presence', 'time': 1688412311.479545, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:25:11,974        INFO         server.py                 client_with_message: <socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>
2023-07-03 22:25:11,974        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688412311.479545, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:25:11,974        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 22:25:11,974        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 22:25:11,975        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 22:25:11,977        DEBUG        server.py                 Auth message = {'response': 511, 'bin': 'c3e0d7ec59a25c07a68141eff812e98632edf540fdef46ce8a0b1a9f357d408bab45f73af8e276063115233918f5bde2901affaf9b95c4619612e36c300c544d'}
2023-07-03 22:25:11,980        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>, {'response': 511, 'bin': 'c3e0d7ec59a25c07a68141eff812e98632edf540fdef46ce8a0b1a9f357d408bab45f73af8e276063115233918f5bde2901affaf9b95c4619612e36c300c544d'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:25:11,982        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:25:11,985        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:25:11,999        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:11,999        INFO         server.py                 response: {'action': 'presence', 'time': 1688412311.481539, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:25:12,000        INFO         server.py                 client_with_message: <socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>
2023-07-03 22:25:12,000        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688412311.481539, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:25:12,000        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 22:25:12,000        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 22:25:12,001        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 22:25:12,002        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '9ed89d54be29c9b0793c464c26869e58c4a59fd1ff21b9ccd7466a6b50bf30816f526699c89c8de15e26dc226e261e6fd21e2682ed772880ed769d166d89a169'}
2023-07-03 22:25:12,005        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>, {'response': 511, 'bin': '9ed89d54be29c9b0793c464c26869e58c4a59fd1ff21b9ccd7466a6b50bf30816f526699c89c8de15e26dc226e261e6fd21e2682ed772880ed769d166d89a169'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:25:12,007        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:25:12,010        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:25:12,529        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:12,529        INFO         server.py                 response: {'action': 'get_users', 'time': 1688412311.9845307, 'account_name': 'test1'}
2023-07-03 22:25:12,529        INFO         server.py                 client_with_message: <socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>
2023-07-03 22:25:12,529        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688412311.9845307, 'account_name': 'test1'}
2023-07-03 22:25:12,532        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:25:12,534        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:12,534        INFO         server.py                 response: {'action': 'get_users', 'time': 1688412312.0104625, 'account_name': 'test2'}
2023-07-03 22:25:12,534        INFO         server.py                 client_with_message: <socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>
2023-07-03 22:25:12,534        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688412312.0104625, 'account_name': 'test2'}
2023-07-03 22:25:12,537        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:25:13,046        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:13,046        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688412312.542205, 'user': 'test1'}
2023-07-03 22:25:13,047        INFO         server.py                 client_with_message: <socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>
2023-07-03 22:25:13,047        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688412312.542205, 'user': 'test1'}
2023-07-03 22:25:13,061        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:25:13,072        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:13,072        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688412312.5451958, 'user': 'test2'}
2023-07-03 22:25:13,073        INFO         server.py                 client_with_message: <socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>
2023-07-03 22:25:13,073        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688412312.5451958, 'user': 'test2'}
2023-07-03 22:25:13,084        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:25:39,065        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:39,065        INFO         server.py                 response: {'action': 'add', 'time': 1688412338.6368272, 'user': 'test1', 'account_name': 'test2'}
2023-07-03 22:25:39,065        INFO         server.py                 client_with_message: <socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>
2023-07-03 22:25:39,065        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'add', 'time': 1688412338.6368272, 'user': 'test1', 'account_name': 'test2'}
2023-07-03 22:25:39,088        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:25:45,706        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:45,707        INFO         server.py                 response: {'action': 'add', 'time': 1688412345.7010007, 'user': 'test2', 'account_name': 'test1'}
2023-07-03 22:25:45,707        INFO         server.py                 client_with_message: <socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>
2023-07-03 22:25:45,707        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'add', 'time': 1688412345.7010007, 'user': 'test2', 'account_name': 'test1'}
2023-07-03 22:25:45,720        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:25:50,829        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:25:50,829        INFO         server.py                 response: {'action': 'pubkey_need', 'time': 1688412350.3515348, 'account_name': 'test2'}
2023-07-03 22:25:50,829        INFO         server.py                 client_with_message: <socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>
2023-07-03 22:25:50,830        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'pubkey_need', 'time': 1688412350.3515348, 'account_name': 'test2'}
2023-07-03 22:25:50,838        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:26:09,622        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:26:09,622        INFO         server.py                 response: {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688412369.367695, 'mess_text': 'A7IN8/pP/IQ5RBCtNxRQwH1SRgGetsICd3IWCFg9OL+H6aPv6IOQtT4UZDaPt85DF+PsrCy2m/z86lvapd+v+akQjHwpHiUg8uSM7+g9h8dLKCyj5BALvZZhrWyOCf9rAju23Wrh7Ao0MWPU9Eof3Sf1Hre8dSjskdbhq7JgIzEYbEATKG2HjLBI+cdgsC+kObFLzTejjNBnyrXS8bh7p9ozcB/oDS2pORl/3ILrnJ79juNCCzV7eEuUSp6D1tdA5AJAtQCPPBNC7IRKeVoYOLc1sq0dSKwLk71Sit3Bov0eA4updkQT4cJ6TQjtTSPN0JjTjQ1G8hiFGwkKhk+e/A=='}
2023-07-03 22:26:09,623        INFO         server.py                 client_with_message: <socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>
2023-07-03 22:26:09,623        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688412369.367695, 'mess_text': 'A7IN8/pP/IQ5RBCtNxRQwH1SRgGetsICd3IWCFg9OL+H6aPv6IOQtT4UZDaPt85DF+PsrCy2m/z86lvapd+v+akQjHwpHiUg8uSM7+g9h8dLKCyj5BALvZZhrWyOCf9rAju23Wrh7Ao0MWPU9Eof3Sf1Hre8dSjskdbhq7JgIzEYbEATKG2HjLBI+cdgsC+kObFLzTejjNBnyrXS8bh7p9ozcB/oDS2pORl/3ILrnJ79juNCCzV7eEuUSp6D1tdA5AJAtQCPPBNC7IRKeVoYOLc1sq0dSKwLk71Sit3Bov0eA4updkQT4cJ6TQjtTSPN0JjTjQ1G8hiFGwkKhk+e/A=='}
2023-07-03 22:26:09,638        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1776, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52431)>, {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688412369.367695, 'mess_text': 'A7IN8/pP/IQ5RBCtNxRQwH1SRgGetsICd3IWCFg9OL+H6aPv6IOQtT4UZDaPt85DF+PsrCy2m/z86lvapd+v+akQjHwpHiUg8uSM7+g9h8dLKCyj5BALvZZhrWyOCf9rAju23Wrh7Ao0MWPU9Eof3Sf1Hre8dSjskdbhq7JgIzEYbEATKG2HjLBI+cdgsC+kObFLzTejjNBnyrXS8bh7p9ozcB/oDS2pORl/3ILrnJ79juNCCzV7eEuUSp6D1tdA5AJAtQCPPBNC7IRKeVoYOLc1sq0dSKwLk71Sit3Bov0eA4updkQT4cJ6TQjtTSPN0JjTjQ1G8hiFGwkKhk+e/A=='}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-03 22:26:09,638        INFO         server.py                 Отправлено сообщение пользователю test2 от пользователя test1.
2023-07-03 22:26:09,640        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:26:10,150        DEBUG        server.py                 Getting data from client exception.
Traceback (most recent call last):
  File "D:\projects\pythonProject\server\server.py", line 370, in run
    response = get_message(client_with_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\decorators.py", line 19, in wrap
    ret = func_log(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\utils.py", line 20, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-07-03 22:26:10,153        INFO         server.py                 Клиент ('127.0.0.1', 52431) отключился от сервера.
2023-07-03 22:33:56,725        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:33:56,725        INFO         server.py                 response: {'action': 'exit', 'time': 1688412836.2668, 'account_name': 'test1'}
2023-07-03 22:33:56,725        INFO         server.py                 client_with_message: <socket.socket fd=1772, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52430)>
2023-07-03 22:33:56,726        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'exit', 'time': 1688412836.2668, 'account_name': 'test1'}
2023-07-03 22:33:56,726        INFO         server.py                 Клиент ('127.0.0.1', 52430) отключился от сервера.
2023-07-03 22:35:14,508        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:35:14,508        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 22:35:14,510        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 22:35:14,510        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 22:35:14,548        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 22:35:38,040        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52512)
2023-07-03 22:35:38,042        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52513)
2023-07-03 22:35:38,551        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:35:38,551        INFO         server.py                 response: {'action': 'presence', 'time': 1688412938.053962, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:35:38,551        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>
2023-07-03 22:35:38,564        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688412938.053962, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:35:38,564        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 22:35:38,565        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 22:35:38,572        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 22:35:38,575        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '8e2047918545b3880fc899954fa9a421f4f02e2b4e6ef764aa02853d54e8470cf5591de700e189a0fcfd3734dc3c251960143ce92bcde0fe717f336cbb3a8f8a'}
2023-07-03 22:35:38,578        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>, {'response': 511, 'bin': '8e2047918545b3880fc899954fa9a421f4f02e2b4e6ef764aa02853d54e8470cf5591de700e189a0fcfd3734dc3c251960143ce92bcde0fe717f336cbb3a8f8a'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:35:38,581        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:35:38,584        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:35:38,605        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:35:38,605        INFO         server.py                 response: {'action': 'presence', 'time': 1688412938.0559573, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:35:38,605        INFO         server.py                 client_with_message: <socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>
2023-07-03 22:35:38,605        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688412938.0559573, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 22:35:38,605        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 22:35:38,605        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 22:35:38,607        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 22:35:38,608        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '8d40a349910a923265cd70fbf8b0f03dbf574b6da7e1c573d286d3752a8d291e7039735de151ac25fa1ff5f0363e61ed9bd15814fb32dda727db3958129e33fb'}
2023-07-03 22:35:38,612        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>, {'response': 511, 'bin': '8d40a349910a923265cd70fbf8b0f03dbf574b6da7e1c573d286d3752a8d291e7039735de151ac25fa1ff5f0363e61ed9bd15814fb32dda727db3958129e33fb'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:35:38,615        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:35:38,619        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 22:35:39,141        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:35:39,141        INFO         server.py                 response: {'action': 'get_users', 'time': 1688412938.584936, 'account_name': 'test1'}
2023-07-03 22:35:39,141        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>
2023-07-03 22:35:39,142        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688412938.584936, 'account_name': 'test1'}
2023-07-03 22:35:39,144        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:35:39,145        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:35:39,145        INFO         server.py                 response: {'action': 'get_users', 'time': 1688412938.618156, 'account_name': 'test2'}
2023-07-03 22:35:39,145        INFO         server.py                 client_with_message: <socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>
2023-07-03 22:35:39,145        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688412938.618156, 'account_name': 'test2'}
2023-07-03 22:35:39,148        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:35:39,658        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:35:39,659        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688412939.156758, 'user': 'test1'}
2023-07-03 22:35:39,659        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>
2023-07-03 22:35:39,660        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688412939.156758, 'user': 'test1'}
2023-07-03 22:35:39,678        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>, {'response': 202, 'data_list': ['test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:35:39,683        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:35:39,683        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688412939.1577597, 'user': 'test2'}
2023-07-03 22:35:39,684        INFO         server.py                 client_with_message: <socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>
2023-07-03 22:35:39,684        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688412939.1577597, 'user': 'test2'}
2023-07-03 22:35:39,690        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>, {'response': 202, 'data_list': ['test1']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:35:49,413        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:35:49,413        INFO         server.py                 response: {'action': 'pubkey_need', 'time': 1688412949.044081, 'account_name': 'test2'}
2023-07-03 22:35:49,413        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>
2023-07-03 22:35:49,413        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'pubkey_need', 'time': 1688412949.044081, 'account_name': 'test2'}
2023-07-03 22:35:49,416        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:36:11,841        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:36:11,842        INFO         server.py                 response: {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688412971.0517738, 'mess_text': 'eOGpsNgvT2qz3RvDIDUsFwl4qEo1AeAVuRPwJmP6bYlySTThTFD/azjO3Ofie+YfIR9yTjKrBvwGvV4CTcbiR2qmcCgn7MaAfVQq+727Sd56aGsAMg9sZGPzHVMYdM6gu88l/1DrLfiJE04BD5XIFWYJ+EtC0Yv+NlxpDtg6Rd8fZfH2MiXhf04U4ExIi0ucAgLVK8Xm8QqAUuzmXb59SiPuOvf/dyyoTNGf3D2qCkIQvVpv7SJ2yGqEhb0vm73kVwN0I8/SPYGH+bNuqAKHN/4F0aWdBojfZ1Fx5ZnMaOaIwH43R4VsXDDP4iEbbJnvcDgJo2YpPaF3r38hLN9WjQ=='}
2023-07-03 22:36:11,843        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>
2023-07-03 22:36:11,843        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688412971.0517738, 'mess_text': 'eOGpsNgvT2qz3RvDIDUsFwl4qEo1AeAVuRPwJmP6bYlySTThTFD/azjO3Ofie+YfIR9yTjKrBvwGvV4CTcbiR2qmcCgn7MaAfVQq+727Sd56aGsAMg9sZGPzHVMYdM6gu88l/1DrLfiJE04BD5XIFWYJ+EtC0Yv+NlxpDtg6Rd8fZfH2MiXhf04U4ExIi0ucAgLVK8Xm8QqAUuzmXb59SiPuOvf/dyyoTNGf3D2qCkIQvVpv7SJ2yGqEhb0vm73kVwN0I8/SPYGH+bNuqAKHN/4F0aWdBojfZ1Fx5ZnMaOaIwH43R4VsXDDP4iEbbJnvcDgJo2YpPaF3r38hLN9WjQ=='}
2023-07-03 22:36:11,860        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1304, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52513)>, {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688412971.0517738, 'mess_text': 'eOGpsNgvT2qz3RvDIDUsFwl4qEo1AeAVuRPwJmP6bYlySTThTFD/azjO3Ofie+YfIR9yTjKrBvwGvV4CTcbiR2qmcCgn7MaAfVQq+727Sd56aGsAMg9sZGPzHVMYdM6gu88l/1DrLfiJE04BD5XIFWYJ+EtC0Yv+NlxpDtg6Rd8fZfH2MiXhf04U4ExIi0ucAgLVK8Xm8QqAUuzmXb59SiPuOvf/dyyoTNGf3D2qCkIQvVpv7SJ2yGqEhb0vm73kVwN0I8/SPYGH+bNuqAKHN/4F0aWdBojfZ1Fx5ZnMaOaIwH43R4VsXDDP4iEbbJnvcDgJo2YpPaF3r38hLN9WjQ=='}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-03 22:36:11,861        INFO         server.py                 Отправлено сообщение пользователю test2 от пользователя test1.
2023-07-03 22:36:11,863        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 22:36:12,876        DEBUG        server.py                 Getting data from client exception.
Traceback (most recent call last):
  File "D:\projects\pythonProject\server\server.py", line 370, in run
    response = get_message(client_with_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\decorators.py", line 19, in wrap
    ret = func_log(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\utils.py", line 20, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-07-03 22:36:12,878        INFO         server.py                 Клиент ('127.0.0.1', 52513) отключился от сервера.
2023-07-03 22:36:24,035        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 22:36:24,036        INFO         server.py                 response: {'action': 'exit', 'time': 1688412983.532997, 'account_name': 'test1'}
2023-07-03 22:36:24,036        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52512)>
2023-07-03 22:36:24,036        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'exit', 'time': 1688412983.532997, 'account_name': 'test1'}
2023-07-03 22:36:24,037        INFO         server.py                 Клиент ('127.0.0.1', 52512) отключился от сервера.
2023-07-03 23:34:59,393        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 23:34:59,394        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 23:34:59,395        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 23:34:59,396        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 23:34:59,475        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 23:35:17,455        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52831)
2023-07-03 23:35:17,465        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52832)
2023-07-03 23:35:17,972        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:17,973        INFO         server.py                 response: {'action': 'presence', 'time': 1688416517.467971, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:35:17,973        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>
2023-07-03 23:35:17,982        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688416517.467971, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:35:17,982        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 23:35:17,982        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 23:35:17,988        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 23:35:17,990        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '6aa894783b6df0b725c20299be5d448fc0131e3bdcb7ad0d68256fca741f8be62ebabe718dfb302b95a98bd3cc72be2a6b104bd5bac31dc982c285af4ca4a26b'}
2023-07-03 23:35:17,992        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>, {'response': 511, 'bin': '6aa894783b6df0b725c20299be5d448fc0131e3bdcb7ad0d68256fca741f8be62ebabe718dfb302b95a98bd3cc72be2a6b104bd5bac31dc982c285af4ca4a26b'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:35:17,994        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:35:17,995        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:35:18,010        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:18,010        INFO         server.py                 response: {'action': 'presence', 'time': 1688416517.4750814, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:35:18,010        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>
2023-07-03 23:35:18,010        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688416517.4750814, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:35:18,010        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 23:35:18,010        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 23:35:18,011        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 23:35:18,012        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '6e1c9dd110df366eee952fa37e54f65550aefa9c276377ffc074752a3d841d5541c3335a56f3c716241281e0d660a8940a216b573006db493690aad07cdb79d8'}
2023-07-03 23:35:18,014        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>, {'response': 511, 'bin': '6e1c9dd110df366eee952fa37e54f65550aefa9c276377ffc074752a3d841d5541c3335a56f3c716241281e0d660a8940a216b573006db493690aad07cdb79d8'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:35:18,016        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:35:18,019        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:35:18,536        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:18,536        INFO         server.py                 response: {'action': 'get_users', 'time': 1688416517.9956367, 'account_name': 'test1'}
2023-07-03 23:35:18,536        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>
2023-07-03 23:35:18,536        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688416517.9956367, 'account_name': 'test1'}
2023-07-03 23:35:18,540        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:35:18,542        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:18,542        INFO         server.py                 response: {'action': 'get_users', 'time': 1688416518.0188148, 'account_name': 'test2'}
2023-07-03 23:35:18,542        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>
2023-07-03 23:35:18,542        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688416518.0188148, 'account_name': 'test2'}
2023-07-03 23:35:18,545        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:35:19,048        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:19,048        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688416518.5508642, 'user': 'test1'}
2023-07-03 23:35:19,048        INFO         server.py                 client_with_message: <socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>
2023-07-03 23:35:19,048        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688416518.5508642, 'user': 'test1'}
2023-07-03 23:35:19,053        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>, {'response': 202, 'data_list': ['test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:35:19,055        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:19,055        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688416518.556121, 'user': 'test2'}
2023-07-03 23:35:19,055        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>
2023-07-03 23:35:19,055        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688416518.556121, 'user': 'test2'}
2023-07-03 23:35:19,059        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>, {'response': 202, 'data_list': ['test1']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:35:26,706        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:26,706        INFO         server.py                 response: {'action': 'pubkey_need', 'time': 1688416526.5292788, 'account_name': 'test1'}
2023-07-03 23:35:26,706        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>
2023-07-03 23:35:26,706        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'pubkey_need', 'time': 1688416526.5292788, 'account_name': 'test1'}
2023-07-03 23:35:26,709        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:35:48,111        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:35:48,111        INFO         server.py                 response: {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1688416547.5451055, 'mess_text': 'I2WIm8cA4jZYKzjYlysanRA6iW2RIZw/mv4BOhVNKSYxJixa4M6YMxI1+AftOWhFCKflE34tLLL/aRUPwu9GPgBHAXvFqTEc/9MxGSi6AQU5VPv22fV42qIWGecp3f0wE/SLJKR86UCf2schRYzlvwCTQGBkHTJIWjHSoLY51K50jEsOeFW0/pm7Xyfyu1+ZHueT0vUwJ53MRPGNdtqydDMbllyD2nsSW5yrIQQRhdtlNjyfD5gZOfRgxiTRtSsN35kjEjKBL4Lw2fkk1LAx0cuyNj89erEIPo2IYRE0IfTgilf8ZypK++xVRHeKjFRoK8J1IaTiTIM8pVYeoabfkA=='}
2023-07-03 23:35:48,111        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>
2023-07-03 23:35:48,112        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1688416547.5451055, 'mess_text': 'I2WIm8cA4jZYKzjYlysanRA6iW2RIZw/mv4BOhVNKSYxJixa4M6YMxI1+AftOWhFCKflE34tLLL/aRUPwu9GPgBHAXvFqTEc/9MxGSi6AQU5VPv22fV42qIWGecp3f0wE/SLJKR86UCf2schRYzlvwCTQGBkHTJIWjHSoLY51K50jEsOeFW0/pm7Xyfyu1+ZHueT0vUwJ53MRPGNdtqydDMbllyD2nsSW5yrIQQRhdtlNjyfD5gZOfRgxiTRtSsN35kjEjKBL4Lw2fkk1LAx0cuyNj89erEIPo2IYRE0IfTgilf8ZypK++xVRHeKjFRoK8J1IaTiTIM8pVYeoabfkA=='}
2023-07-03 23:35:48,128        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1312, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52831)>, {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1688416547.5451055, 'mess_text': 'I2WIm8cA4jZYKzjYlysanRA6iW2RIZw/mv4BOhVNKSYxJixa4M6YMxI1+AftOWhFCKflE34tLLL/aRUPwu9GPgBHAXvFqTEc/9MxGSi6AQU5VPv22fV42qIWGecp3f0wE/SLJKR86UCf2schRYzlvwCTQGBkHTJIWjHSoLY51K50jEsOeFW0/pm7Xyfyu1+ZHueT0vUwJ53MRPGNdtqydDMbllyD2nsSW5yrIQQRhdtlNjyfD5gZOfRgxiTRtSsN35kjEjKBL4Lw2fkk1LAx0cuyNj89erEIPo2IYRE0IfTgilf8ZypK++xVRHeKjFRoK8J1IaTiTIM8pVYeoabfkA=='}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-03 23:35:48,128        INFO         server.py                 Отправлено сообщение пользователю test1 от пользователя test2.
2023-07-03 23:35:48,129        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:35:49,147        DEBUG        server.py                 Getting data from client exception.
Traceback (most recent call last):
  File "D:\projects\pythonProject\server\server.py", line 370, in run
    response = get_message(client_with_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\decorators.py", line 19, in wrap
    ret = func_log(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\utils.py", line 20, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-07-03 23:35:49,148        INFO         server.py                 Клиент ('127.0.0.1', 52831) отключился от сервера.
2023-07-03 23:36:02,941        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:36:02,941        INFO         server.py                 response: {'action': 'exit', 'time': 1688416562.6420991, 'account_name': 'test2'}
2023-07-03 23:36:02,941        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52832)>
2023-07-03 23:36:02,942        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'exit', 'time': 1688416562.6420991, 'account_name': 'test2'}
2023-07-03 23:36:02,942        INFO         server.py                 Клиент ('127.0.0.1', 52832) отключился от сервера.
2023-07-03 23:54:18,966        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 23:54:18,967        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 23:54:18,969        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 23:54:18,970        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 23:54:19,001        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-03 23:54:34,189        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52919)
2023-07-03 23:54:34,198        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52920)
2023-07-03 23:54:34,702        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:54:34,702        INFO         server.py                 response: {'action': 'presence', 'time': 1688417674.1999333, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:54:34,702        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>
2023-07-03 23:54:34,712        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688417674.1999333, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:54:34,712        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 23:54:34,712        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 23:54:34,720        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 23:54:34,722        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '9e08e152b338057a84c982044f512e885e1828f43ddc50902c4a0665f32e28f86f4ce8b8dae7912e824e7c6dda29a3eed1240cfb72f2b3eeea55afe26bff544a'}
2023-07-03 23:54:34,725        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>, {'response': 511, 'bin': '9e08e152b338057a84c982044f512e885e1828f43ddc50902c4a0665f32e28f86f4ce8b8dae7912e824e7c6dda29a3eed1240cfb72f2b3eeea55afe26bff544a'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:54:34,728        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:54:34,732        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:54:34,974        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:54:34,975        INFO         server.py                 response: {'action': 'presence', 'time': 1688417674.2090003, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:54:34,975        INFO         server.py                 client_with_message: <socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>
2023-07-03 23:54:34,975        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688417674.2090003, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-03 23:54:34,975        INFO         server.py                 Обрабатываем PRESENCE
2023-07-03 23:54:34,975        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-03 23:54:34,977        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-03 23:54:34,978        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '3f99c677cebae3d670d7a3714c0ae03c86dd5640c69eee9bc0879c836085efabcb6b3a21da2abf0c8350993efb95b3a1b6f1994f6dce77f144deb6a90baf424a'}
2023-07-03 23:54:34,981        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>, {'response': 511, 'bin': '3f99c677cebae3d670d7a3714c0ae03c86dd5640c69eee9bc0879c836085efabcb6b3a21da2abf0c8350993efb95b3a1b6f1994f6dce77f144deb6a90baf424a'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:54:34,984        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:54:34,987        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-03 23:54:35,514        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:54:35,514        INFO         server.py                 response: {'action': 'get_users', 'time': 1688417674.7312415, 'account_name': 'test1'}
2023-07-03 23:54:35,514        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>
2023-07-03 23:54:35,514        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688417674.7312415, 'account_name': 'test1'}
2023-07-03 23:54:35,517        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:54:35,518        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:54:35,518        INFO         server.py                 response: {'action': 'get_users', 'time': 1688417674.98712, 'account_name': 'test2'}
2023-07-03 23:54:35,518        INFO         server.py                 client_with_message: <socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>
2023-07-03 23:54:35,518        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688417674.98712, 'account_name': 'test2'}
2023-07-03 23:54:35,520        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:54:36,027        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:54:36,027        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688417675.5318975, 'user': 'test1'}
2023-07-03 23:54:36,027        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>
2023-07-03 23:54:36,027        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688417675.5318975, 'user': 'test1'}
2023-07-03 23:54:36,032        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>, {'response': 202, 'data_list': ['test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:54:36,033        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:54:36,033        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688417675.5309002, 'user': 'test2'}
2023-07-03 23:54:36,033        INFO         server.py                 client_with_message: <socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>
2023-07-03 23:54:36,033        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688417675.5309002, 'user': 'test2'}
2023-07-03 23:54:36,036        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>, {'response': 202, 'data_list': ['test1']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:54:46,197        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:54:46,197        INFO         server.py                 response: {'action': 'pubkey_need', 'time': 1688417685.9729133, 'account_name': 'test2'}
2023-07-03 23:54:46,197        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>
2023-07-03 23:54:46,198        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'pubkey_need', 'time': 1688417685.9729133, 'account_name': 'test2'}
2023-07-03 23:54:46,200        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:55:21,822        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:55:21,822        INFO         server.py                 response: {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688417721.3370202, 'mess_text': 'S44Ou/rVrm8qrSdhHQzKB5Zb4hP1w2bbznsQXGQd2V9kBi3hINYVAqJ0tdgd8TbPsU1x6CFT60N1FBUW0oc5rXgwxiR06kkEQRKjCtC2Lzjd+jJiPBSoF1NNateESoEGnbB+EC6g7nOjGcfc95SaOY7DMxcp2qyxlsfxQcE6Rb3EJNfdLFo+ChuX1WPve02tX2IULwIZl28aRq8p7Fk4lW9EtEYs3XwCZndfP4YAGfss+QezlaBrDBkb7H9PNaOSTWKLfbEA5+/w4v9XZpG8qwZUX0TYWh3zP2dLMhLqBkwKKb/qMiE9kbXcCNT4heOlpG3iLnlsB4q6QkKWmPkWKw=='}
2023-07-03 23:55:21,822        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>
2023-07-03 23:55:21,822        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688417721.3370202, 'mess_text': 'S44Ou/rVrm8qrSdhHQzKB5Zb4hP1w2bbznsQXGQd2V9kBi3hINYVAqJ0tdgd8TbPsU1x6CFT60N1FBUW0oc5rXgwxiR06kkEQRKjCtC2Lzjd+jJiPBSoF1NNateESoEGnbB+EC6g7nOjGcfc95SaOY7DMxcp2qyxlsfxQcE6Rb3EJNfdLFo+ChuX1WPve02tX2IULwIZl28aRq8p7Fk4lW9EtEYs3XwCZndfP4YAGfss+QezlaBrDBkb7H9PNaOSTWKLfbEA5+/w4v9XZpG8qwZUX0TYWh3zP2dLMhLqBkwKKb/qMiE9kbXcCNT4heOlpG3iLnlsB4q6QkKWmPkWKw=='}
2023-07-03 23:55:21,838        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1324, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52920)>, {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688417721.3370202, 'mess_text': 'S44Ou/rVrm8qrSdhHQzKB5Zb4hP1w2bbznsQXGQd2V9kBi3hINYVAqJ0tdgd8TbPsU1x6CFT60N1FBUW0oc5rXgwxiR06kkEQRKjCtC2Lzjd+jJiPBSoF1NNateESoEGnbB+EC6g7nOjGcfc95SaOY7DMxcp2qyxlsfxQcE6Rb3EJNfdLFo+ChuX1WPve02tX2IULwIZl28aRq8p7Fk4lW9EtEYs3XwCZndfP4YAGfss+QezlaBrDBkb7H9PNaOSTWKLfbEA5+/w4v9XZpG8qwZUX0TYWh3zP2dLMhLqBkwKKb/qMiE9kbXcCNT4heOlpG3iLnlsB4q6QkKWmPkWKw=='}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-03 23:55:21,838        INFO         server.py                 Отправлено сообщение пользователю test2 от пользователя test1.
2023-07-03 23:55:21,840        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-03 23:55:22,857        DEBUG        server.py                 Getting data from client exception.
Traceback (most recent call last):
  File "D:\projects\pythonProject\server\server.py", line 370, in run
    response = get_message(client_with_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\decorators.py", line 19, in wrap
    ret = func_log(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\utils.py", line 20, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2023-07-03 23:55:22,858        INFO         server.py                 Клиент ('127.0.0.1', 52920) отключился от сервера.
2023-07-03 23:55:50,440        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-03 23:55:50,440        INFO         server.py                 response: {'action': 'exit', 'time': 1688417750.0068932, 'account_name': 'test1'}
2023-07-03 23:55:50,440        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52919)>
2023-07-03 23:55:50,440        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'exit', 'time': 1688417750.0068932, 'account_name': 'test1'}
2023-07-03 23:55:50,440        INFO         server.py                 Клиент ('127.0.0.1', 52919) отключился от сервера.
2023-07-03 23:59:47,555        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 23:59:47,556        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-03 23:59:47,557        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-03 23:59:47,558        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-03 23:59:47,585        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-04 00:00:06,556        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52951)
2023-07-04 00:00:06,559        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52952)
2023-07-04 00:00:07,074        DEBUG        server.py                 Getting data from client exception.
Traceback (most recent call last):
  File "D:\projects\pythonProject\server\server.py", line 370, in run
    response = get_message(client_with_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\decorators.py", line 19, in wrap
    ret = func_log(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\utils.py", line 20, in get_message
    encoded_response = client.recv()
                       ^^^^^^^^^^^^^
TypeError: recv() takes at least 1 argument (0 given)
2023-07-04 00:00:07,075        INFO         server.py                 Клиент ('127.0.0.1', 52951) отключился от сервера.
2023-07-04 00:00:07,075        DEBUG        server.py                 Getting data from client exception.
Traceback (most recent call last):
  File "D:\projects\pythonProject\server\server.py", line 370, in run
    response = get_message(client_with_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\decorators.py", line 19, in wrap
    ret = func_log(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\pythonProject\server\utils.py", line 20, in get_message
    encoded_response = client.recv()
                       ^^^^^^^^^^^^^
TypeError: recv() takes at least 1 argument (0 given)
2023-07-04 00:00:07,076        INFO         server.py                 Клиент ('127.0.0.1', 52952) отключился от сервера.
2023-07-04 00:00:56,345        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-04 00:00:56,345        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-04 00:00:56,346        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-04 00:00:56,347        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-04 00:00:56,376        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-04 00:02:49,381        DEBUG        server.py                 Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-04 00:02:49,382        DEBUG        server.py                 Инициализация парсера аргументов командной строки: ['server/server.py']
2023-07-04 00:02:49,383        DEBUG        server.py                 Аргументы успешно загружены.
2023-07-04 00:02:49,384        DEBUG        server.py                 Была вызвана функция arg_parser c параметрами ('8079', ''), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции main
2023-07-04 00:02:49,411        INFO         server.py                 Запущен сервер, порт для подключений: 8079 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-07-04 00:03:00,526        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52965)
2023-07-04 00:03:00,535        INFO         server.py                 Установлено соединение с ПК ('127.0.0.1', 52966)
2023-07-04 00:03:01,039        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:01,039        INFO         server.py                 response: {'action': 'presence', 'time': 1688418180.5520062, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-04 00:03:01,039        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>
2023-07-04 00:03:01,049        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688418180.5520062, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-04 00:03:01,049        INFO         server.py                 Обрабатываем PRESENCE
2023-07-04 00:03:01,049        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-04 00:03:01,058        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-04 00:03:01,061        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '372ef7b9464d50ada99e989703cd874bfe7a5adf89c3192dc28515deaa20283447b079ce9c605784d27e7178ba38e0aa109aa41b36ef7572ef4b1727136a1e27'}
2023-07-04 00:03:01,064        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>, {'response': 511, 'bin': '372ef7b9464d50ada99e989703cd874bfe7a5adf89c3192dc28515deaa20283447b079ce9c605784d27e7178ba38e0aa109aa41b36ef7572ef4b1727136a1e27'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-04 00:03:01,067        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-04 00:03:01,070        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-04 00:03:01,089        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:01,090        INFO         server.py                 response: {'action': 'presence', 'time': 1688418180.5450253, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-04 00:03:01,090        INFO         server.py                 client_with_message: <socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>
2023-07-04 00:03:01,090        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'presence', 'time': 1688418180.5450253, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2023-07-04 00:03:01,090        INFO         server.py                 Обрабатываем PRESENCE
2023-07-04 00:03:01,090        DEBUG        server.py                 Начало процесса авторизации для пользователя {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}
2023-07-04 00:03:01,092        DEBUG        server.py                 Correct username, starting passwd check.
2023-07-04 00:03:01,093        DEBUG        server.py                 Auth message = {'response': 511, 'bin': '42687ea0bced3f52f63fd60da2cae6002e9d3d0857e72ede602f0a12e385b2ec99f76d3987d7ca270d42f5ccb8ca7880c7c0c3e1823c4ec25755acea7cdd57e9'}
2023-07-04 00:03:01,096        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>, {'response': 511, 'bin': '42687ea0bced3f52f63fd60da2cae6002e9d3d0857e72ede602f0a12e385b2ec99f76d3987d7ca270d42f5ccb8ca7880c7c0c3e1823c4ec25755acea7cdd57e9'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-04 00:03:01,099        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-04 00:03:01,102        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2023-07-04 00:03:01,619        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:01,619        INFO         server.py                 response: {'action': 'get_users', 'time': 1688418181.0705757, 'account_name': 'test1'}
2023-07-04 00:03:01,619        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>
2023-07-04 00:03:01,620        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688418181.0705757, 'account_name': 'test1'}
2023-07-04 00:03:01,623        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:03:01,624        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:01,624        INFO         server.py                 response: {'action': 'get_users', 'time': 1688418181.1024907, 'account_name': 'test2'}
2023-07-04 00:03:01,624        INFO         server.py                 client_with_message: <socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>
2023-07-04 00:03:01,624        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_users', 'time': 1688418181.1024907, 'account_name': 'test2'}
2023-07-04 00:03:01,628        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>, {'response': 202, 'data_list': ['test1', 'test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:03:02,142        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:02,142        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688418181.6347983, 'user': 'test1'}
2023-07-04 00:03:02,142        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>
2023-07-04 00:03:02,143        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688418181.6347983, 'user': 'test1'}
2023-07-04 00:03:02,147        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>, {'response': 202, 'data_list': ['test2']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:03:02,149        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:02,149        INFO         server.py                 response: {'action': 'get_contacts', 'time': 1688418181.6377897, 'user': 'test2'}
2023-07-04 00:03:02,149        INFO         server.py                 client_with_message: <socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>
2023-07-04 00:03:02,149        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'get_contacts', 'time': 1688418181.6377897, 'user': 'test2'}
2023-07-04 00:03:02,152        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>, {'response': 202, 'data_list': ['test1']}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:03:10,848        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:10,848        INFO         server.py                 response: {'action': 'pubkey_need', 'time': 1688418190.5650911, 'account_name': 'test1'}
2023-07-04 00:03:10,848        INFO         server.py                 client_with_message: <socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>
2023-07-04 00:03:10,848        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'pubkey_need', 'time': 1688418190.5650911, 'account_name': 'test1'}
2023-07-04 00:03:10,851        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKN/CFSxgU8eu0oO0oKw\n29WTZQSfqw/mJgEtr8nLUAOHGcg3kT7epUgPfwbo/V67sJlGhb/UD7dPK81utWRn\nFKhhUGuo+ad/4HnvbSQjIHy2Wbr85T4gJCL1IqTkodAgSOo4Nuv/Qq9r5po0dNIC\nF4YTZrzfCy6V0v349iXM2CXf+/14fHCxsm3OkNCUwHsOW6nzh5fIyAs1UhssJm/Z\nbCNzX5PkRjI7bwBJhoXHNgS1fDyII6vGrQAyAwxU0hKrBAtAzYIon5ZlIYxyF2/5\nKb8IVmLmnrvCpmtjTQ4u80Dp6YuErMCD82GzgUi50UdQoW617AmFxaKpvO7Lu+aA\nfwIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:03:13,405        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:03:13,405        INFO         server.py                 response: {'action': 'pubkey_need', 'time': 1688418192.9187992, 'account_name': 'test2'}
2023-07-04 00:03:13,406        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>
2023-07-04 00:03:13,406        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'pubkey_need', 'time': 1688418192.9187992, 'account_name': 'test2'}
2023-07-04 00:03:13,408        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtrfkZ/5Xtj72x44QP9b5\neTenYYlSJkkb6X+jL4pqATUwGcvvcxBDtRrR0j1VZzhdlUvetoA3MvecULu3jTvg\nRhcrRHQRIzgMSjNV9ZGFBqhZvQmwGJEDI72dAjLyb1e5t1fT45o2DRfA+Zgxt+N0\ntTIgV7xIQiJrkGkaTje1oXqa9a1MH3o2bMLyrnfv2FE3SKdEQK5GUy+ec0P42QUx\njQ4GG2tEVYHJHS8tiQ+Rwz2Qcubs2YeqmLiUP6ZNdRLEZxn4YN0YNsTPEYzre2qo\n/nAAuWSixjOzt8OQQoSlOjL+VcDZBTitNSmnCMtjcVeTj36J5jUsc3onQofaWf1M\npQIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:04:08,076        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:04:08,076        INFO         server.py                 response: {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1688418247.7083018, 'mess_text': 'R7sCGz3ij0Ipt8qJdabKCh46eakaOHxOZrNH9HTvbe6Nyhwi2o25SbVOozOgvhC9NQgd4REzxY6KRjyUavtWFo+YBPbtGobss8JrZVMo9aXenb82REXF4Ao1nJmnxnj/XjAFt/zkJJmNbMwg1/BAQIOq+M/hulWVNNxl8lakLQbjF6W1GoL9jnmFlirf+8P3ZJfHGNrfQ+f6SjFyv1m40zYaDJP9yZKF11sBlxAabJHw1pyFoCBhnzI8w8rvS8TajtemrEmlmmzq3VN3qAZHizHXmyqm58VqjkjRAa1R0H5q/p7gm+bc84lCzBuCcEY9+pJE6/3cZkq7LgzDtiKUDQ=='}
2023-07-04 00:04:08,076        INFO         server.py                 client_with_message: <socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>
2023-07-04 00:04:08,076        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1688418247.7083018, 'mess_text': 'R7sCGz3ij0Ipt8qJdabKCh46eakaOHxOZrNH9HTvbe6Nyhwi2o25SbVOozOgvhC9NQgd4REzxY6KRjyUavtWFo+YBPbtGobss8JrZVMo9aXenb82REXF4Ao1nJmnxnj/XjAFt/zkJJmNbMwg1/BAQIOq+M/hulWVNNxl8lakLQbjF6W1GoL9jnmFlirf+8P3ZJfHGNrfQ+f6SjFyv1m40zYaDJP9yZKF11sBlxAabJHw1pyFoCBhnzI8w8rvS8TajtemrEmlmmzq3VN3qAZHizHXmyqm58VqjkjRAa1R0H5q/p7gm+bc84lCzBuCcEY9+pJE6/3cZkq7LgzDtiKUDQ=='}
2023-07-04 00:04:08,142        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>, {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1688418247.7083018, 'mess_text': 'R7sCGz3ij0Ipt8qJdabKCh46eakaOHxOZrNH9HTvbe6Nyhwi2o25SbVOozOgvhC9NQgd4REzxY6KRjyUavtWFo+YBPbtGobss8JrZVMo9aXenb82REXF4Ao1nJmnxnj/XjAFt/zkJJmNbMwg1/BAQIOq+M/hulWVNNxl8lakLQbjF6W1GoL9jnmFlirf+8P3ZJfHGNrfQ+f6SjFyv1m40zYaDJP9yZKF11sBlxAabJHw1pyFoCBhnzI8w8rvS8TajtemrEmlmmzq3VN3qAZHizHXmyqm58VqjkjRAa1R0H5q/p7gm+bc84lCzBuCcEY9+pJE6/3cZkq7LgzDtiKUDQ=='}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-04 00:04:08,142        INFO         server.py                 Отправлено сообщение пользователю test1 от пользователя test2.
2023-07-04 00:04:08,145        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:05:15,557        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:05:15,557        INFO         server.py                 response: {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688418315.3327773, 'mess_text': 'eczLE5kWFGxcqD5NA3O8PjVhJ0xg+8zZHpJKktZQdAHERjMpRayXIj7BddZJbTIXZSYhy8b4rDS4r8YGdjt2xtR8v3akpdgr51nTSeV+ZE4bmzQRqFHWsN6UkHh0ESJPDrEXGgenb4Dzp5ax9cXV7FZMfdlT4yk/PVLdLMew47GpAPh7peRKnEBV8ZN4DZqSKB+c0zWzru3KIoGvI9F7mYdhy1kmS/4UGu+eEirMISXJtfGZBXt59vEuXh+FKhhY/04F81UnBPfZRaEJAZ2IL/HIgBP4qDR8sUq4bbjCyCVfx0RwCXr2VYYQPVwFMizPqPy9VzgNzQ3l8Mh1AqJShw=='}
2023-07-04 00:05:15,557        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>
2023-07-04 00:05:15,557        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688418315.3327773, 'mess_text': 'eczLE5kWFGxcqD5NA3O8PjVhJ0xg+8zZHpJKktZQdAHERjMpRayXIj7BddZJbTIXZSYhy8b4rDS4r8YGdjt2xtR8v3akpdgr51nTSeV+ZE4bmzQRqFHWsN6UkHh0ESJPDrEXGgenb4Dzp5ax9cXV7FZMfdlT4yk/PVLdLMew47GpAPh7peRKnEBV8ZN4DZqSKB+c0zWzru3KIoGvI9F7mYdhy1kmS/4UGu+eEirMISXJtfGZBXt59vEuXh+FKhhY/04F81UnBPfZRaEJAZ2IL/HIgBP4qDR8sUq4bbjCyCVfx0RwCXr2VYYQPVwFMizPqPy9VzgNzQ3l8Mh1AqJShw=='}
2023-07-04 00:05:15,621        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>, {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1688418315.3327773, 'mess_text': 'eczLE5kWFGxcqD5NA3O8PjVhJ0xg+8zZHpJKktZQdAHERjMpRayXIj7BddZJbTIXZSYhy8b4rDS4r8YGdjt2xtR8v3akpdgr51nTSeV+ZE4bmzQRqFHWsN6UkHh0ESJPDrEXGgenb4Dzp5ax9cXV7FZMfdlT4yk/PVLdLMew47GpAPh7peRKnEBV8ZN4DZqSKB+c0zWzru3KIoGvI9F7mYdhy1kmS/4UGu+eEirMISXJtfGZBXt59vEuXh+FKhhY/04F81UnBPfZRaEJAZ2IL/HIgBP4qDR8sUq4bbjCyCVfx0RwCXr2VYYQPVwFMizPqPy9VzgNzQ3l8Mh1AqJShw=='}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-04 00:05:15,621        INFO         server.py                 Отправлено сообщение пользователю test2 от пользователя test1.
2023-07-04 00:05:15,623        DEBUG        server.py                 Была вызвана функция send_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>, {'response': 200}), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2023-07-04 00:05:39,083        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:05:39,083        INFO         server.py                 response: {'action': 'exit', 'time': 1688418338.921632, 'account_name': 'test1'}
2023-07-04 00:05:39,083        INFO         server.py                 client_with_message: <socket.socket fd=1316, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52965)>
2023-07-04 00:05:39,083        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'exit', 'time': 1688418338.921632, 'account_name': 'test1'}
2023-07-04 00:05:39,084        INFO         server.py                 Клиент ('127.0.0.1', 52965) отключился от сервера.
2023-07-04 00:05:42,161        DEBUG        server.py                 Была вызвана функция get_message c параметрами (<socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>,), {}. Вызов из модуля utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-04 00:05:42,161        INFO         server.py                 response: {'action': 'exit', 'time': 1688418341.7936833, 'account_name': 'test2'}
2023-07-04 00:05:42,161        INFO         server.py                 client_with_message: <socket.socket fd=1288, family=2, type=1, proto=0, laddr=('127.0.0.1', 8079), raddr=('127.0.0.1', 52966)>
2023-07-04 00:05:42,161        DEBUG        server.py                 Получено сообщение от клиента : {'action': 'exit', 'time': 1688418341.7936833, 'account_name': 'test2'}
2023-07-04 00:05:42,161        INFO         server.py                 Клиент ('127.0.0.1', 52966) отключился от сервера.
